=== danieljfgoncalves/rolhas-xml-xslt/xsd/rolhas.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="xml.lprog.isep.pt/rolhas"
           elementFormDefault="qualified"
           xmlns:tn="xml.lprog.isep.pt/tastingNotes"
           xmlns:ct="xml.lprog.isep.pt/complexTypes"
           xmlns:st="xml.lprog.isep.pt/simpleTypes">

    <!-- INCLUDES & IMPORTS -->
    <xs:import namespace="xml.lprog.isep.pt/tastingNotes" schemaLocation="tastingNotes.xsd"/>
    <xs:import namespace="xml.lprog.isep.pt/complexTypes" schemaLocation="complexTypes.xsd"/>
    <xs:import namespace="xml.lprog.isep.pt/simpleTypes" schemaLocation="simpleTypes.xsd"/>
    <!-- MAIN SCHEMA -->
    <xs:element name="o_rolhas">
        <xs:complexType>
            <xs:sequence>
                <!-- WINES SCHEMA -->
                <xs:element name="wines">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="wine" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="name" type="st:stringWithFirstCapType"/>
                                        <xs:element name="price" type="ct:priceType"/>
                                        <xs:element name="producer" type="st:stringWithFirstCapType"/>
                                        <xs:element name="origin">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="country" type="ct:countryType"/>
                                                    <xs:element name="region" type="st:stringWithFirstCapType"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="technical_sheet">
                                            <xs:complexType>
                                                <xs:all>
                                                    <xs:element name="alchool_content" type="st:nonNegativeFloatType"/>
                                                    <xs:element name="sweetness">
                                                        <xs:complexType mixed="true">
                                                            <xs:sequence>
                                                                <xs:element name="sweetness_content"
                                                                            type="ct:sweetnessContentType"/>
                                                                <xs:element name="sweetness_descriptor"
                                                                            type="ct:sweetnessDescriptorType"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="varietal" type="st:stringWithFirstCapType"/>
                                                    <xs:element name="style" type="st:stringWithFirstCapType"/>
                                                </xs:all>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="package" type="ct:packageType"/>
                                        <xs:element name="image" type="ct:imageType"/>
                                    </xs:all>
                                    <xs:attribute name="reference" type="xs:positiveInteger" use="required"/>
                                    <xs:attribute name="tasting_note_id" type="xs:positiveInteger"/> <!-- OPTIONAL -->
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <!-- TASTING NOTES SCHEMA -->
                <xs:element name="tasting_notes" type="tn:tastingNotesType" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="logo" type="xs:anyURI"/> <!-- OPTIONAL -->
        </xs:complexType>
    </xs:element>

</xs:schema>

=== danieljfgoncalves/rolhas-xml-xslt/xml/rolhas.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<o_rolhas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="xml.lprog.isep.pt/rolhas /xsd/rolhas.xsd"
          xmlns="xml.lprog.isep.pt/rolhas">
    <wines> <!-- root element -->
        <wine reference="12781" tasting_note_id="1">
            <name>Mateus Rosé</name>
            <price currency="euro">16.64</price>
            <producer>Sogrape</producer>
            <origin>
                <country acronym="PT">Portugal</country>
                <region>Douro</region>
            </origin>
            <technical_sheet>
                <alchool_content>11.0</alchool_content>
                <sweetness>
                    A very sweet wine (<sweetness_content unit="g/L">19</sweetness_content>g/L) described as
                    <sweetness_descriptor acronym="M" designation="Medium"/>
                    sweet
                </sweetness>
                <varietal>Rosé</varietal>
                <style>Soft &amp; Off-dry</style>
            </technical_sheet>
            <package unit="mL">1500</package>
            <image full="resources/full_image/mateus_rose_full"
                   thumb="resources/thumb_image/mateus_rose_thumb"/>
        </wine>
        <wine reference="286195">
            <name>Jp Azeitão Red</name>
            <origin>
                <country acronym="PT">Portugal</country>
                <region>Setubal</region>
            </origin>
            <producer>Bacalhoa Vinhos de Portugal, S.A.</producer>
            <price currency="euro">8.94</price>
            <technical_sheet>
                <alchool_content>13.5</alchool_content>
                <sweetness>
                    <sweetness_content unit="g/L">4</sweetness_content>
                    <sweetness_descriptor acronym="XD" designation="Extra Dry"/>
                </sweetness>
                <varietal>Red Blend</varietal>
                <style>Medium-bodied &amp; Fruity</style>
            </technical_sheet>
            <package type="bottle" unit="mL">750</package>
            <image full="resources/full_image/jp_azeitao_red_full"
                   thumb="resources/thumb_image/jp_azeitao_red_thumb"/>
        </wine>
        <wine reference="589069">
            <name>French Cross Red Bag in Box</name>
            <origin>
                <country acronym="CA">Canada</country>
                <region>Region Not Specified</region>
            </origin>
            <producer>Andres Wines Ltd</producer>
            <price currency="euro">33.95</price>
            <technical_sheet>
                <alchool_content>11.5</alchool_content>
                <sweetness>
                    <sweetness_content unit="g/L">9</sweetness_content>
                    <sweetness_descriptor acronym="D" designation="Dry"/>
                </sweetness>
                <varietal>Blend</varietal>
                <style>Medium-bodied &amp; Fruity</style>
            </technical_sheet>
            <package type="bagnbox" unit="mL">4000</package>
            <image full="resources/full_image/french_cross_red_bag_in_box_full"
                   thumb="resources/thumb_image/french_cross_red_bag_in_box_thumb"/>
        </wine>
        <wine reference="229542">
            <name>Folonari Pinot Grigio</name>
            <origin>
                <country acronym="IT">Italy</country>
                <region>Veneto</region>
            </origin>
            <producer>Folonari S.P.A.</producer>
            <price currency="euro">10.95</price>
            <technical_sheet>
                <alchool_content>11.5</alchool_content>
                <sweetness>
                    <sweetness_content unit="g/L">6</sweetness_content>
                    <sweetness_descriptor acronym="XD" designation="Extra Dry"/>
                </sweetness>
                <varietal>Pinot Grigio</varietal>
                <style>Light &amp; Crisp</style>
            </technical_sheet>
            <package type="bottle" unit="mL">750</package>
            <image full="resources/full_image/folonari_pinot_grigio_full"
                   thumb="resources/thumb_image/folonari_pinot_grigio_thumb"/>
        </wine>

    </wines>
    <tasting_notes xmlns:tn="xml.lprog.isep.pt/tastingNotes">
        <tn:tasting_note id="1" lang="EN">
            Mateus Rosé Original is a rosé with a very appealing and bright hue. On the whole,
            it is a fresh and seductive wine with fine and intense bouquet and all the joviality
            of young wines. In the mouth, it is a well balanced and tempting wine, brilliantly
            complemented by a soft and slightly fizzy finish.
        </tn:tasting_note>
    </tasting_notes>
</o_rolhas>
